transcription_set= ['sampa', 'ipa', 'manner', 'place']

languages = {
    'australian english': 'eng-AU',
    'south african afrikaans': 'afr-ZA',
    'albanian': 'sqi-AL',
    'arabic': 'arb',
    'basque (spain)': 'eus-ES',
    'basque (france)': 'eus-FR',
    'catalan': 'cat-ES',
    'czech': 'cze-CZ',
    'dutch': 'nld-NL',
    'british english': 'eng-GB',
    'new zealand english': 'eng-NZ',
    'american english': 'eng-US',
    'estonian': 'ekk-EE',
    'finnish': 'fin-FI',
    'french': 'fra-FR',
    'georgian': 'kat-GE',
    'german': 'deu-DE',
    'swiss german': 'gsw-CH',
    'swiss german (bern)': 'gsw-CH-BE',
    'swiss german (basel)': 'gsw-CH-BS',
    'swiss german (graubünden)': 'gsw-CH-GR',
    'swiss german (st. gallen)': 'gsw-CH-SG',
    'swiss german (zurich)': 'gsw-CH-ZH',
    'haitian creole': 'hat-HT',
    'hungarian': 'hun-HU',
    'icelandic': 'isl-IS',
    'italian': 'ita-IT',
    'japanese': 'jpn-JP',
    'guugu yimithirr': 'gup-AU',
    'luxembourgish': 'ltz-LU',
    'maltese': 'mlt-MT',
    'norwegian': 'nor-NO',
    'persian': 'fas-IR',
    'polish': 'pol-PL',
    'romanian': 'ron-RO',
    'russian': 'rus-RU',
    'slovak': 'slk-SK',
    'spanish': 'spa-ES',
    'swedish': 'swe-SE',
    'thai': 'tha-TH',
    'gungabula': 'guf-AU',
    'unknown': 'und',
}

